# Generated by Django 4.0.3 on 2022-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_workflow_engine", "0004_auto_20211116_0823"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskrecord",
            old_name="finished_at",
            new_name="executed_at",
        ),
    ]
