# Generated by Django 4.0.3 on 2022-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_workflow_engine", "0006_taskrecord_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="running",
            field=models.BooleanField(default=False),
        ),
    ]
