# Generated by Django 4.1.3 on 2023-03-08 15:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_workflow_engine",
            "0009_rename_taskrecord_taskrecordexecution_and_create_new_taskstatus",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(null=True)),
                ("step_id", models.CharField(max_length=100)),
                ("task_name", models.CharField(max_length=100)),
                ("task_info", models.JSONField(default=dict)),
                ("done", models.BooleanField(default=False)),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="django_workflow_engine.flow",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="target",
            name="task_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="django_workflow_engine.taskstatus",
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="task_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log",
                to="django_workflow_engine.taskstatus",
            ),
        ),
        migrations.RenameField(
            model_name="target",
            old_name="task_record",
            new_name="task_status",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_record",
            new_name="task_status",
        ),
    ]
